global:
  tlsDisable: true
ui:
  enabled: true
server:
  dev:
    enabled: true
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }